<a href="https://colab.research.google.com/github/Mohd-Ali2/Projects/blob/main/House_price_predeicting01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Impoting Libraries**

In [28]:
import numpy as np
import pandas as pd

# **Checking we've have Null Values or not !**

In [29]:
df.isnull().sum()

SquareFeet      0
Bedrooms        0
Bathrooms       0
Neighborhood    0
YearBuilt       0
Price           0
dtype: int64

# **Loading Dataset**

In [30]:
df = pd.read_csv("housing_price_dataset.csv")
x = df.iloc[:, : -1].values
y = df.iloc[:, -1].values

# **Categorical** **Encoding**

In [31]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-2])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [32]:
print(x)

[[1.0 0.0 0.0 ... 4 1 1969]
 [1.0 0.0 0.0 ... 3 2 1980]
 [0.0 1.0 0.0 ... 2 1 1970]
 ...
 [0.0 1.0 0.0 ... 5 3 1962]
 [1.0 0.0 0.0 ... 5 2 1984]
 [1.0 0.0 0.0 ... 5 3 2011]]


# **Spliting Data into Training and Test**

In [33]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

# **Training Model (LinearRegression)**

In [34]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train, y_train)

LinearRegression()

# **Predicting Test Values (Predicted Values VS Actual Values)**

In [35]:
y_pred = reg.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[272348.09 273143.34]
 [128251.86 202150.47]
 [279761.24 313958.04]
 ...
 [123826.63 127591.26]
 [286656.12 335605.52]
 [184333.25 171773.49]]
