<a href="https://colab.research.google.com/github/Mohd-Ali2/Projects/blob/main/House_price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [14]:
df.isnull().sum()

SquareFeet      0
Bedrooms        0
Bathrooms       0
Neighborhood    0
YearBuilt       0
Price           0
dtype: int64

In [5]:
df = pd.read_csv("housing_price_dataset.csv")
x = df.iloc[:, : -1].values
y = df.iloc[:, -1].values

array([[2126, 4, 1, 'Rural', 1969],
       [2459, 3, 2, 'Rural', 1980],
       [1860, 2, 1, 'Suburb', 1970],
       ...,
       [2979, 5, 3, 'Suburb', 1962],
       [2596, 5, 2, 'Rural', 1984],
       [1572, 5, 3, 'Rural', 2011]], dtype=object)

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-2])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [10]:
print(x)

[[1.0 0.0 0.0 ... 4 1 1969]
 [1.0 0.0 0.0 ... 3 2 1980]
 [0.0 1.0 0.0 ... 2 1 1970]
 ...
 [0.0 1.0 0.0 ... 5 3 1962]
 [1.0 0.0 0.0 ... 5 2 1984]
 [1.0 0.0 0.0 ... 5 3 2011]]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [12]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train, y_train)

LinearRegression()

In [13]:
y_pred = reg.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[272348.09 273143.34]
 [128251.86 202150.47]
 [279761.24 313958.04]
 ...
 [123826.63 127591.26]
 [286656.12 335605.52]
 [184333.25 171773.49]]
